# Generated by Django 5.2.3 on 2025-06-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ltf', models.TextField(blank=True, help_text='LTF Chart URL')),
                ('htf', models.TextField(blank=True, help_text='HTF Chart URL')),
                ('bias', models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell'), ('', 'Not Set')], max_length=10)),
                ('array', models.CharField(blank=True, choices=[('FVG', 'Fair Value Gap'), ('Asian High Low', 'Asian High Low'), ('OB', 'Order Block'), ('', 'Not Set')], max_length=50)),
                ('pnl', models.DecimalField(decimal_places=2, default=0, help_text='Profit and Loss', max_digits=10)),
                ('emotions', models.CharField(blank=True, choices=[('Confident', 'Confident'), ('Anxious', 'Anxious'), ('Excited', 'Excited'), ('Fearful', 'Fearful'), ('Greedy', 'Greedy'), ('Patient', 'Patient'), ('Frustrated', 'Frustrated'), ('Calm', 'Calm'), ('Overconfident', 'Overconfident'), ('Disciplined', 'Disciplined'), ('FOMO', 'FOMO'), ('Revenge Trading', 'Revenge Trading'), ('Neutral', 'Neutral'), ('', 'Not Set')], max_length=50)),
                ('mistake', models.TextField(blank=True, help_text='What went wrong?')),
                ('reason', models.TextField(blank=True, help_text='Why did you take this trade?')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
