# Generated by Django 5.2.1 on 2025-08-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_journalentry_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='array',
            field=models.TextField(blank=True, help_text='Comma-separated array values'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='emotions',
            field=models.TextField(blank=True, help_text='Comma-separated emotion values'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='results',
            field=models.TextField(blank=True, help_text='Comma-separated result values'),
        ),
    ]
