# Generated by Django 5.1 on 2025-09-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_journalentry_array_alter_journalentry_emotions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='after_trade_emotions',
            field=models.TextField(blank=True, help_text='Comma-separated emotion values', null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='before_trade_emotions',
            field=models.TextField(blank=True, help_text='Comma-separated emotion values', null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='in_trade_emotions',
            field=models.TextField(blank=True, help_text='Comma-separated emotion values', null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='emotions',
            field=models.TextField(blank=True, help_text='Comma-separated emotion values', null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mistake',
            field=models.TextField(blank=True, help_text='Comma-separated emotion values', null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reason',
            field=models.TextField(blank=True, help_text='Why did you take this trade?', null=True),
        ),
    ]
