# Generated by Django 5.2.3 on 2025-09-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_journalentry_after_trade_emotions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='kil_zone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
