# Generated by Django 5.2.3 on 2025-09-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_journalentry_kil_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='kil_zone',
            new_name='kill_zone',
        ),
    ]
