# Generated by Django 5.2.3 on 2025-09-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_kil_zone_journalentry_kill_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='bias',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
